{
 "title": "WebRTC Internals Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(peer_connection_timestamp,exported_job)"
    }
   },
   {
    "name": "pageUrl",
    "label": "URL",
    "query": {
     "query": "label_values(peer_connection_timestamp,pageUrl)"
    }
   },
   {
    "name": "peerConnectionId",
    "label": "PeerConnection",
    "query": {
     "query": "label_values(peer_connection_timestamp,peerConnectionId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peer Connections",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "peer_connection_timestamp{pageUrl=\"$pageUrl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outbound Audio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(outbound_rtp_bytesSent{exported_job=\"$job\", kind=\"audio\", pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FractionLost",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "remote_inbound_rtp_fractionLost{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RoundTripTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "remote_inbound_rtp_roundTripTime{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "remote_inbound_rtp_jitter{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(outbound_rtp_packetsSent{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outbound Video", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(outbound_rtp_bytesSent{exported_job=\"$job\", kind=\"video\", pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FractionLost",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "remote_inbound_rtp_fractionLost{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RoundTripTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "remote_inbound_rtp_roundTripTime{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "remote_inbound_rtp_jitter{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QualityLimitationDurations (bandwidth)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "outbound_rtp_qualityLimitationDurations_bandwidth{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QualityLimitationDurations (cpu)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "outbound_rtp_qualityLimitationDurations_cpu{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FrameWidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "outbound_rtp_frameWidth{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FrameHeight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "outbound_rtp_frameHeight{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FramesPerSecond",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "outbound_rtp_framesPerSecond{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TargetBitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "outbound_rtp_targetBitrate{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(outbound_rtp_packetsSent{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retransmitted packet rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(outbound_rtp_retransmittedPacketsSent{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inbound Audio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(inbound_rtp_bytesReceived{exported_job=\"$job\", kind=\"audio\", pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PacketsLossRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "inbound_rtp_packetsLost{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}\n/ (inbound_rtp_packetsLost{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"} + inbound_rtp_packetsReceived{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "inbound_rtp_jitter{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JitterBufferDelay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "inbound_rtp_jitterBufferDelay{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"} / inbound_rtp_jitterBufferEmittedCount{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(inbound_rtp_packetsReceived{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"audio\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inbound Video", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(inbound_rtp_bytesReceived{exported_job=\"$job\", kind=\"video\", pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PacketsLossRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "inbound_rtp_packetsLost{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}\n/ (inbound_rtp_packetsLost{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"} + inbound_rtp_packetsReceived{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "inbound_rtp_jitter{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JitterBufferDelay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "inbound_rtp_jitterBufferDelay{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"} / inbound_rtp_jitterBufferEmittedCount{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent PLI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "inbound_rtp_pliCount{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FrameWidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "inbound_rtp_frameWidth{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FrameHeight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "inbound_rtp_frameHeight{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FramesPerSecond",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "inbound_rtp_framesPerSecond{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalFreezesDuration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "inbound_rtp_totalFreezesDuration{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(inbound_rtp_packetsReceived{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\", exported_job=\"$job\", kind=\"video\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outbound Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(data_channel_bytesSent{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(data_channel_messagesSent{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inbound data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(data_channel_bytesReceived{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(data_channel_messagesReceived{pageUrl=\"$pageUrl\", peerConnectionId=~\"$peerConnectionId\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}